### ISSUE TITLE
Slow page routing during development.

### ISSUE THREAD

**Issue by Keshavdulal** [colbyfayock/next-wordpress-starter#168]
Dear Maintainers,
I recently began using this repo for a project of mine.
I tested the `production builds` at first.
The pages were 👌 blazingly fast with the Wordpress setup.
So I began to work on `development mode` and that's where I encountered very slow routing of around 4-6 seconds in average and even in incognito.

<img width="1680" alt="Screen Shot 2021-05-18 at 7 40 49 PM" src="https://user-images.githubusercontent.com/16687310/118669837-cdb5cd80-b815-11eb-8a13-72295bcb3868.png">

_Filtered Network Tab showing time taken to get the json file for the page from wordpress._

<img width="1680" alt="Screen Shot 2021-05-18 at 7 41 17 PM" src="https://user-images.githubusercontent.com/16687310/118669859-d27a8180-b815-11eb-9bb0-27b005a7b902.png">

_Network Tab showing all the requests._

**Here's what I did.**
1. Installed Wordpress using Local App from WpEngine and setup a test site `Foobar`.
2. Installed WpGraphQL plugin.
3. Installed [WP Lorem Ipsum](https://wordpress.org/plugins/wp-lorem-ipsum/) plugin which helped me to generate dummy pages(10) and dummy blog posts(10).
4. I then forked this starter repo and then cloned it using `git clone`
5. Install packages using `yarn`
6. Set the graphql endpoint in `env.local` as `WORDPRESS_GRAPHQL_ENDPOINT="http://foobar.local/graphql"`
7. I then tested the production build first using `yarn build && yarn start` which worked like a charm.
8. Then I thought of playing around in the development. I ran `yarn dev` and that's where I found that all the pages load very slowly. They are even slower than the actual Wordpress site as well so I thought there must be something going on.

Here's my console logs.
![image](https://user-images.githubusercontent.com/16687310/118672621-1cfcfd80-b818-11eb-903c-929f3914c3bc.png)

& Here's my repo. https://github.com/Keshavdulal/next-wordpress-starter

From my guess/research so far it's something to do with Fast Refresh and HMR maybe but I am not sure so I thought of reaching you guys here. I am fairly new to WordPress & NextJS but seasoned in React.
Let me know If I am missing something during setup. Any insights are welcomed. 🙌

**Comment by Keshavdulal** [comment]
Additional Information.
I also tried the ["minmal version of this repo"](https://github.com/colbyfayock/next-wpgraphql-basic-starter).
It performed quite better with an average of around `1.3 seconds` for the same Wordpress setup.

Here are some snapshots.

<img width="1680" alt="Screen Shot 2021-05-18 at 8 43 57 PM" src="https://user-images.githubusercontent.com/16687310/118674970-f17b1280-b819-11eb-9d5c-566a319646dc.png">

_Filtered Network Tab showing time taken to get the json file for the page from wordpress._

<img width="1680" alt="Screen Shot 2021-05-18 at 8 44 15 PM" src="https://user-images.githubusercontent.com/16687310/118674987-f63fc680-b819-11eb-868f-f8346800b729.png">

_Console logs for the development build_

**Comment by doingandlearning** [comment]
Hey - thanks for reaching out!

In production, a lot of the logic work that happens in getStaticProps is handled at build time. During development, this is refreshed during each Fast Refresh - so all of those lovely `Successfully created` messages are from quite a lot of heavy lifting when it comes to each refresh. Alongside that, the getInitialProps in `_app.js` is doing a lot of work.

I wonder if there is a "rapid development" option or similar that could minimise these features if you weren't working directly with them.

**Comment by Keshavdulal** [comment]
@doingandlearning Thanks for clarifying that bit regarding `getStaticProps` and `getInitialProps`.
I am digging into them right now.

And even I wonder if there's a way to minimize such delays during development as that might be a deal breaker to use the starter for long term projects.

Hoping to hear from @colbyfayock as well :)

**Comment by colbyfayock** [comment]
yeah @doingandlearning @GuilleAngulo and I were chatting about it a bit in my discord https://spacejelly.dev/discord

so a little context, we're currently using `getInitialProps` in a custom `_app.js` to grab globally available data as there really isn't any type of global data layer mechanism to do that right now, beyond adding those requests on each page in something like `getStaticProps`, and i guess setting up a new context or pass those as props each time, which feels like the wrong way to handle it

part of the downside is this is typically discouraged, as it [automatically disables some optimizations](https://nextjs.org/docs/advanced-features/custom-app#caveats). the reason we're thinking it's okay here is because the app ends up being statically compiled anyways, so this is at no cost to the user

now i haven't run any tests to confirm this but i believe that to be the reason why it's slow page to page, because that ends up making all of those requests every time a new page loads, and there are a few in there to get all the relevant WP data

i think a big thing that currently isn't working properly (or might just not be set up) is a caching mechanism for those requests. each time the apollo client is being used, it seems to be creating a new instance, which im guessing means it's also not doing any sort of caching

![image](https://user-images.githubusercontent.com/1045274/118710899-e958ae00-b7ec-11eb-954a-4edf94f78fd9.png)

that wasn't the intent but it didnt seem to work as expected

@GuilleAngulo said he's going to poke at it a bit and see if he can figure anything out. im not a graphql expert but trying to also do a little digging around to see if i can find anything that make ssense as to how to properly set up apollo to take advantage of caching

this article for instances sets up the client a little differently, could help: https://www.apollographql.com/blog/getting-started-with-apollo-client-in-next-js/

More info from their docs: https://www.apollographql.com/docs/react/caching/cache-configuration/

if we can't seem to figure something out i can reach out to people over there and see if they have any recs

**Comment by colbyfayock** [comment]
hey @Keshavdulal just merged in some caching changes. would love to get your thoughts as to how you think that improves things. seems to be much snappier for me. i think the file generation improvements will help as well once they get in

**Comment by Keshavdulal** [comment]
Great! Thanks @colbyfayock.I will check it out and let you know.

**Comment by colbyfayock** [comment]
Closing this, but feel free to reopen if it remains an issue.

**Comment by Keshavdulal** [comment]
_Pardon me coming back at this after so long.
Here's an update incase anyone comes across this._


## This is an issue with the nextjs framework itself.
[Here's an ongoing discussion on Github Issues](https://github.com/vercel/next.js/discussions/10949)

This slow routing issue has nothing much to do with this or any starter for that matter. I tried making one from scratch but faced the same issue.

### My Use Case/Context
I was making some network requests (for global data such as header/footer navigation items) in a `getInitialProps` method at `_app.js` so that those data can be reused across all the pages.
But not so fast.

According to Nextjs Docs as of writing this says: (May be this will change in future)
```
- Adding a custom getInitialProps in your App will disable Automatic Static Optimization in pages without Static Generation.
- App currently does not support Next.js Data Fetching methods like getStaticProps or getServerSideProps.
```

### So, How I solved it?
- I used file-based local data caching mechanism to speed up the slow-routing.
- [Reference Solution Article by Flavio Copes](https://flaviocopes.com/nextjs-cache-data-globally/)

There are other solutions discussed in the github discussion too but the above one worked in my case.
So hope this helps.
