### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#26]
We should generate an RSS feed

Can we take advantage of the work we're already doing for the search index?

**Comment by GuilleAngulo** [comment]
Hey @colbyfayock , I was checking this one. Here is an idea of approach:

1.- Change **getAllPosts** at util.js to retrieve more info, to fill both searchIndex and the feed.
2.- Add new method **generateFeed()** at util.js using [rss](https://www.npmjs.com/package/rss)
3.- At search-index-compiler add a new **outPutDirectory/outPutName** for the feed ('**./.next/static/feed.xml**') 
4.- Use generateFeed at search-index-compiler.
4.- Use _rewrites_ feature at next.config.js:
- source: "/feed.xml",
- destination: "/_next/static/feed.xml",
	
What do you think?

**Comment by colbyfayock** [comment]
what do you think about making this a separate plugin? i like the idea of abstracting these kinds of things because it leaves room for the potential future of pulling them out into separate packages if that's something we could make work. that way, if someone only wants to install search for instance, they could do that easily

id like to hear more about the rewrites feature, is that something we could / should be using with the wp-search.json file as well?

im totally cool with you giving that a shot!

**Comment by GuilleAngulo** [comment]
Absolutely, I've ended up thinking of it as separate plugins. At the same time I was thinking in your first message here, and I realized that the three potential plugins (including sitemap) could share same class compiler because the structure is the same:

1.- Retrieve data
2.- Generate file
3.- Write file

I'll make a PR to show you the approach. Open to any change you may see aproppiate

About rewrites feature, I was researching about and I didn't find an important reason to use it instead of public folder. It think it only complicates the scenario for no valuable reason.

**Comment by colbyfayock** [comment]
now we need to add a link somewhere on the page :) i'll open a ticket for that one
