### ISSUE TITLE
sitemap and rss 404 errors

### ISSUE THREAD

**Issue by alexandruvisan19** [colbyfayock/next-wordpress-starter#317]
Hi, any reasons to why there are sitemap and RSS console errors? I've seen this issue also happening on the example website.
![image](https://user-images.githubusercontent.com/79447321/149671157-ef567550-7660-4294-b247-2d4df4f73f52.png)
thx

**Comment by colbyfayock** [comment]
hey nice find! 

it looks like the issue is because the Next.js Link component will try to prefetch information on a page and I was using that <Link component to link to those 2 files, with the thought that they were still technically available on the same host

seems they should be treated as external links instead to avoid this lookup, about to push up a fix
